django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('piano_project.urls')),
]

piano_project/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views


urlpatterns = [
path('', views.index, name='index'),
path('<slug:slug>/details', views.teacherDetailView.as_view(), name='teacher_details'),
path('teacher/create', views.createTeacher, name='create_teacher'),
path('teacher/update/<slug:slug>', views.updateTeacher, name='update_teacher'),
path('teacher/delete/<slug:slug>', views.deleteTeacher, name='delete_teacher'),
path('accounts/', include('django.contrib.auth.urls')),
path('accounts/register/', views.registerPage, name='register_page')
#path('user/', views.userPage, name='user_page')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

piano_project/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import User

# Create your models here.

class teacher(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    studio = models.CharField(max_length=500)
    message = models.TextField(max_length=2000)
    about = models.TextField(max_length=2000)
    email = models.CharField(max_length=200)
    def __str__(self):
        return self.name
    active = models.BooleanField(default=True)
    phone_number = models.CharField(max_length=20)
    slug = models.SlugField(null=False, unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(teacher, self).save(*args, **kwargs)

    photo = models.ImageField(upload_to='images/')

    

piano_project/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import teacher

class teacherForm(ModelForm):
    class Meta:
        model = teacher
        fields='__all__'
        exclude=['user','slug','active']

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = {'username','email','password1','password2'}

piano_project/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import generic
from .models import *
from .forms import teacherForm, CreateUserForm
from django.contrib import messages
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from .decorators import allowed_users
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
def index(request):
    active_teachers = teacher.objects.all()
    return render(request, 'piano_project/home.html', {'active_teachers':active_teachers})

class teacherDetailView(generic.DetailView):
    model = teacher

@login_required(login_url='login')
@allowed_users(allowed_roles='teacher_role')
def createTeacher(request):
    form = teacherForm()
    
    if request.method == "POST":
        form = teacherForm(request.POST, request.FILES)
        if form.is_valid():
            new_teacher = form.save(commit=False)
            new_teacher.save()
            
            return redirect('teacher_details', slug=new_teacher.slug)
    
    context = {'form': form}
    return render(request, 'piano_project/teacher_form.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles='teacher_role')
def updateTeacher(request, slug):
    target_teacher = teacher.objects.get(slug=slug)

    form = teacherForm(instance=target_teacher)

    if request.method == "POST":
        print("working?")
        form = teacherForm(request.POST, request.FILES, instance=target_teacher)
        if form.is_valid():
            updated_teacher = form.save(commit=False)
            print("Before save:", updated_teacher.name, updated_teacher.slug)
            updated_teacher.slug = slugify(updated_teacher.name)
            updated_teacher.active = True
            print("After save:", updated_teacher.name, updated_teacher.slug)
            updated_teacher.save()
            
            return redirect('teacher_details', slug=updated_teacher.slug)
    
    context = {'form': form}
    return render(request, 'piano_project/teacher_form.html', context)

@login_required(login_url='login')
@allowed_users(allowed_roles='teacher_role')
def deleteTeacher(request, slug):
    teacher_delete = teacher.objects.get(slug=slug)

    if request.method == 'POST':
        teacher_delete.delete()
        return redirect('index')
    else:
        context = {'teacher': teacher_delete}
        return render(request, 'piano_project/delete_teacher.html', context)
    
def registerPage(request):
    form = CreateUserForm(request.POST)

    if form.is_valid():
        user = form.save()
        username = form.cleaned_data.get('username')
        group = Group.objects.get(name='teacher_role')
        user.groups.add(group)
        Teacher = teacher.objects.create(user=user, name=username, slug=slugify(username))
        Teacher.save()

        messages.success(request, 'Account was created for ' + username)
        return redirect('login')
    context={'form':form}
    return render(request, 'registration/register.html', context)

piano_project/templates/piano_project/base_template.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
 <head>
   <title>Luellen-Sipes Piano Lessons</title>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>Bootstrap demo</title>
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
   <style>
      .btn-red {
        background-color: #662222;
        color: white;
        border-color: #662222;
      }
      .btn-green {
        background-color: #226622;
        color: white;
        border-color: #226622;
      }
      .navbar-color {
        background-color: #AAAACC;
        color: white;
        border-color: #AAAACC;
      }
    </style>
 </head>


 <body>
   <div class="container-fluid">


     <!-- Navbar-->
     <nav class="navbar navbar-expand-lg navbar-color">
       <img src="{% static 'images/piano.png' %}" width="110" height="100"style="padding-left: 10px;">
       <div class="container-fluid">
         <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
         </button>
         <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
           <div class="navbar-nav">
             <!--  {% url 'index' %}  is defined in url path to dynamically create url -->
             <a class="nav-link active" aria-current="page" href="{% url 'index' %}">Home</a>
             {% if user.is_authenticated %}
              <form action="{% url 'logout' %}" method="post" style="display: inline;">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.path }}">
                <button type="submit" class="btn btn-link nav-link" style="display: inline; padding: 0; background: none; border: none;">Logout {{ user.get_username }}</button>
              </form>
             {% else %}
               <a class="nav-link" href="{% url 'login' %}?next={{ request.path }}">Login</a>
             {% endif %}
             <a class="nav-link" href="{% url 'register_page' %}?next={{ request.path }}">Sign Up</a>
           </div>
         </div>
       </div>
     </nav>


       <div class="col-sm-10">
         <!-- add block content from html template -->
         {% block content %}
         {% endblock %}
       </div>
     </div>
   </div>
 </body>
</html>

piano_project/templates/piano_project/delete_teacher.html
<!-- inherit from base.html-->
{% extends "piano_project/base_template.html" %}


<!-- Replace block content in base_template.html -->
{% block content %}
<h1>Delete {{teacher.name}}'s Profile?</h1>


<form action="" method="POST">
    {% csrf_token %}
    

    <a id="delete-button" href="{% url 'index'%}" class="btn btn-primary">Cancel</a>
    <input type="submit" name=Submit class="btn btn-delete-red">
</form>


{% endblock %}

piano_project/templates/piano_project/home.html
<!-- inherit from base.html-->
{% extends "piano_project/base_template.html" %}


<!-- Replace block content in base_template.html -->
{% block content %}
    <h1>Home Page</h2>
    {% for i in active_teachers %}
        <div class="p-3 border">
            <li class="list-group-item">Teacher: {{i.name}}
                <p><strong><a href="{% url 'teacher_details' slug=i.slug%}" class="btn btn-green">Details</a>
                </strong></p>
            </li>
        </div>
    {% endfor %}
    {% if user.is_authenticated %}
        <a href="{% url 'create_teacher' %}" class = "btn btn-secondary"> Create </a>
    {%endif%}

{% endblock %}

piano_project/templates/piano_project/index.html
<!-- inherit from base.html-->
{% extends "piano_project/base_template.html" %}


<!-- Replace block content in base_template.html -->
{% block content %}
<h1>Current Test of Piano Website</h1>


<h2>More to come from Zachary Rytting</h2>


{% endblock %}

piano_project/templates/piano_project/teacher_detail.html
<!-- inherit from base.html-->
{% extends "piano_project/base_template.html" %}


<!-- Replace block content in base_template.html -->
{% block content %}
<h1>{{teacher.name}}</h1>
{% if teacher.photo %}
    <img src="{{teacher.photo.url}}" alt="This is a photo of the teacher" width="200" height="200">
{% endif %}
<h2>{{teacher.phone_number}}</h2>
<p>{{teacher.email}}</p>

<p style="font-family: Cambria, 'Times New Roman', serif;"> 
    <div class="p-3 border" style= "background-color: #ffebbb;"> 
        {{teacher.message}}
    </div>
</p>
<p> 
    <div class="p-3 border" style= "background-color: #f5fff5;"> 
        {{teacher.about}}
    </div>
</p>
{% if user.is_authenticated %}
    <a id="update-button" href="{% url 'update_teacher' slug=teacher.slug%}" class = "btn btn-green"> Update </a>

    <a id="delete-button" href="{% url 'delete_teacher' slug=teacher.slug%}" class = "btn btn-red"> Delete </a>
{% endif %}
{% endblock %}

piano_project/templates/piano_project/teacher_form.html
<!-- inherit from base.html-->
{% extends "piano_project/base_template.html" %}


<!-- Replace block content in base_template.html -->
{% block content %}
<h1>Create a New Teacher Profile</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
        <button type="submit" style="margin-top: 20px">Create Profile</button>
        </div>
        <label for="id_name">Name:</label>
        <div>
            {{ form.name }}
        </div>
        <label for="id_studio">Studio:</label>
        <div>
            {{ form.studio }}
        </div>
        <label for="id_email"> Email:</label>
        <div>
            {{ form.email }}
        </div>
        <label for="id_phone_number">Phone Number:</label>
        <div>
            {{ form.phone_number }}
        </div>
        <label for="id_message">Message:</label>
        <div>
            {{ form.message }}
        </div>
        <label for="id_about">About:</label>
        <div>
            {{ form.about }}
        </div>
        <label for="id_photo">Photo:</label>
        <div>
            {{ form.photo }}
        </div>
    </form>
{% endblock %}